### ISSUE TITLE
How to animate the reel horizontally?

### ISSUE THREAD

**Issue by fumatamax** [cia1099/slot_machine_roller#1]
For example I would like to change the horizontal position to rotate the reels. They always rotate vertically and it is perfect for a slot machine, but what happens if I want to make a loot boxes, they rotate horizontally.

**Comment by cia1099** [comment]
Oh, The solution is really flexible.
You can just wrap [RotatedBox](https://api.flutter.dev/flutter/widgets/RotatedBox-class.html) in double/sextuple quarter turn for direction left/right to child. The roller widget will be horizontal. The items in roller also need to compensate reverse rotation to display correct view.
You can try to wrap any rotational widget to achieve what you want.

I hope this can help you.
